### PR TITLE
add ros2_controllers as exec dependency

### LINKED ISSUE #49: Add ros2_controllers as exec_dependency in next Foxy synchronization
Reference to this comment https://github.com/ros-simulation/gazebo_ros2_control/pull/44#discussion_r569765040

Add `effort_controller`, `velocity_controller` and `joint trajectory controller` as `exec_dependency`

### PR DESCRIPTION
**Pull request by Karsten1987**
fixes #49

once merged, I believe this needs a re-release

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
CI will be broken until that package is released into the stable repositories. But if we don't fix this before the next `gazebo_ros2_control` release, the release will go out with a missing dependency. Classic :chicken: and :egg: . I'll approve, but let @ahcorde make the call on what's best here.

**Comment by ahcorde** [comment]
Holding this PR to the next Foxy sync

**Comment by ahcorde** [comment]
Foxy sync is out! Merging!

**Review by ahcorde — APPROVED** [review]
Foxy sync is out!

**Pull request merged**
