### PR TITLE
Updated with recent ros2_control changes

### PR DESCRIPTION
**Pull request by ahcorde**
Updated with recent ros2_control changes

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by guru-florida** [comment]
Thanks @ahcorde!!!  It works!! I just couldnt seem to figure out how to get the startup node configuration right. I even tried to wrap my head around how the switch_controllers() call would work here but just couldnt see it. I still dont quite see it but I will dig into it this weekend.

Do you mind holding off on the PR for a bit? I had some fairly big updates as well, mostly based on ros2_control fixes but also some things I found while studying the code.
* We dont need to keep the local std::vector<double>s for all the joint states and commands anymore. The new RobotHardware class has register_joint() that create JointHandles directly on the DynamicJointState message.
* I have some changes that enable the joint saturation and soft limits including the velocity based ones. I moved the limits config code from init back into registerJointLimits() method where I saw some previous ifdef'd out code and updated with the new limit handles.
* added  comments

There  is a lot of code in default_robot_hw_sim and the logic is fairly complex, 90% of the complexity is in the setup init(). I had to write out a separate text doc to wrap my head around it all. I think a large chunk of the complexity is in the logic between the various control mode setup. How do you feel about me refactoring out the 3 control modes to separate classes? Like PositionJointXX, VelocityJointXX and EffortJointXX where XX is either Interface, Controller or nothing. I can create a draft PR and you can help review.

FYI  I also have a [PR pending in ros2_controls](https://github.com/ros-controls/ros2_control/pull/194) that will remove the shared_ptr parts of the joint handles. It can still work with shared_ptr but not required anymore.

**Comment by guru-florida** [comment]
As per my [comment in #35](https://github.com/ros-simulation/gazebo_ros2_control/pull/35#issuecomment-711486331) I take back my request to hold off and I think this PR should move forward.

**Comment by ahcorde** [comment]
Hi @guru-florida,

thank for your contibution! I have included your suggestions in the code. It's included/restored the pid controller.

Can you have a look ? If you want to make more modification please build on top of this PR.

**Comment by ahcorde** [comment]
Regarding the refactoring, I'm fine with your suggested changes, but I think we should wait until the `ros2_control` and `ros2_controllers` API is more stable.

**Comment by guru-florida** [comment]
Nice! Thank you!  Updates look good but I found a bug in one of my changes....the readSim() called in initSim() needs to be moved outside the loop at the end...readSim() iterates all joints and when number of joints >1 the readSim is called before other joints have been initialized. 

I believe there is a "components" update coming soon and hopefully things will stabilize after that. I'll probably be helping out conversion to components on the joint limits and transmission when that happens. I have a pending PR on transmission parsing too. These are basically the branches you stated in the #3 with updates to sync with latest ros2_controls master, uncrustification, linting, etc.

FYI I am working on getting my humanoid URDF up and simulating with Gazebo now.

**Comment by ahcorde** [comment]
thank you @guru-florida for finding the bug!

Looking forward to see your humanoid! Any gif/image that you can share at this moment ?

**Comment by Briancbn** [comment]
It seems that /joint_states and /states are not updating properly for the postion demo.

**Comment by ahcorde** [comment]
@Briancbn  I can reproduce your issue. I'm looking into it

**Comment by ahcorde** [comment]
@Briancbn  This last commit should fix the issue. Let me know if this works for you too.

**Comment by guru-florida** [comment]
I just had a look. By the looks of your code change, it looks like you are re-fetching the handles for each of the joint interfaces in the readSim. Did you find the joint handles were being invalidated somehow? ....Those joint handles are pointing directly to doubles in the DynamicJointState msg....Oh @%$!! The ol' growth of std::vector reallocating memory and thus invalidating iterators before it. 

For now, I am going to test setting up the handles as normal, but delay the fetching of those references until after the initSim loop completes. At that point the msg vectors dont grow.

FYI This bug was also popping up in the limit handles enforce_limits() which also binds to those handles.

This IMO is a design flaw in RobotHardware and registering joint-handles as it presents unexpected behavior to the API user due to an inner implementation detail of std:vector. Possibly this will be solved with the new components work going into ros2_controls but we can bring it up in the next working group meeting.

**Comment by Briancbn** [comment]
> @Briancbn This last commit should fix the issue. Let me know if this works for you too.

Thanks so much it works! Probably the best way tho, hahaha.

> FYI This bug was also popping up in the limit handles enforce_limits() which also binds to those handles.

I also notice this as well, for now I am just commenting this line out.

**Comment by guru-florida** [comment]
@ahcorde The transmission parser code has been merged into ros2_control master. I have the changes to update this branch. I will issue a PR from my branch to this one.

**Comment by guru-florida** [comment]
@ahcorde PR #38 is ready for merging into this branch. Also fixed up CI script to no longer do the ddengster branch checkout and overwrite. We have a gazebo plugin that runs directly on ros2_control masters!!! ....at least until they break it....and they will. :)

**Review by chapulina — COMMENTED** [review]
It builds fine, and the position demo works for me.

But the velocity demo doesn't work. What I did:

```
ros2 launch gazebo_ros2_control_demos cart_example_velocity.launch.py &
# wait for simulation to launch
ros2 run gazebo_ros2_control_demos example_velocity
```

Am I missing something?

**Comment by guru-florida** [comment]
@ahcorde I added PR #40 to fix the velocity controller example. Tested with position, position_pid and velocity examples.

@chapulina Thank you for taking the time to review.

**Comment by ahcorde** [comment]
@guru-florida thank you for the fix ;)

@chapulina do you mind to try again ?

**Review by chapulina — APPROVED** [review]
Nice, all the demos work for me now! I didn't work closely at the code, but functionality-wise LGTM!

**Pull request merged**
